# Generated by Django 2.0.3 on 2018-04-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answersCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
