# Generated by Django 2.0.3 on 2018-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180402_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='answersCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questions.Tag'),
        ),
    ]
