# Generated by Django 2.0.3 on 2018-04-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180402_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answersCount',
        ),
    ]
