# Generated by Django 2.0.3 on 2018-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_t',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
